name: First workflow

on: push
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check out repository code
        run: echo "Checking out code..."
